<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\assets\css\bootstrap-icons.min.css" />
    <None Include="wwwroot\assets\css\bootstrap.min.css" />
    <None Include="wwwroot\assets\css\fonts\bootstrap-icons.woff" />
    <None Include="wwwroot\assets\css\fonts\bootstrap-icons.woff2" />
    <None Include="wwwroot\assets\css\price_range_style.css" />
    <None Include="wwwroot\assets\images\favicon.png" />
    <None Include="wwwroot\assets\images\gallery\apple-play-store.png" />
    <None Include="wwwroot\assets\images\gallery\auth\forgot-password.png" />
    <None Include="wwwroot\assets\images\gallery\auth\login.png" />
    <None Include="wwwroot\assets\images\gallery\auth\register.png" />
    <None Include="wwwroot\assets\images\gallery\blog\01.png" />
    <None Include="wwwroot\assets\images\gallery\blog\02.png" />
    <None Include="wwwroot\assets\images\gallery\blog\03.png" />
    <None Include="wwwroot\assets\images\gallery\blog\04.png" />
    <None Include="wwwroot\assets\images\gallery\blog\05.png" />
    <None Include="wwwroot\assets\images\gallery\blog\06.png" />
    <None Include="wwwroot\assets\images\gallery\blog\07.png" />
    <None Include="wwwroot\assets\images\gallery\brands\01.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\02.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\03.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\04.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\05.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\06.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\07.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\08.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\09.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\10.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\11.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\12.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\13.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\14.webp" />
    <None Include="wwwroot\assets\images\gallery\brands\15.webp" />
    <None Include="wwwroot\assets\images\gallery\categories\01.png" />
    <None Include="wwwroot\assets\images\gallery\categories\02.png" />
    <None Include="wwwroot\assets\images\gallery\categories\03.png" />
    <None Include="wwwroot\assets\images\gallery\categories\04.png" />
    <None Include="wwwroot\assets\images\gallery\categories\05.png" />
    <None Include="wwwroot\assets\images\gallery\categories\06.png" />
    <None Include="wwwroot\assets\images\gallery\categories\circular-categories\01.png" />
    <None Include="wwwroot\assets\images\gallery\categories\circular-categories\02.png" />
    <None Include="wwwroot\assets\images\gallery\categories\circular-categories\03.png" />
    <None Include="wwwroot\assets\images\gallery\categories\circular-categories\04.png" />
    <None Include="wwwroot\assets\images\gallery\categories\circular-categories\05.png" />
    <None Include="wwwroot\assets\images\gallery\categories\circular-categories\06.png" />
    <None Include="wwwroot\assets\images\gallery\categories\circular-categories\07.png" />
    <None Include="wwwroot\assets\images\gallery\categories\circular-categories\08.png" />
    <None Include="wwwroot\assets\images\gallery\categories\circular-categories\09.png" />
    <None Include="wwwroot\assets\images\gallery\categories\circular-categories\10.png" />
    <None Include="wwwroot\assets\images\gallery\categories\circular-categories\11.png" />
    <None Include="wwwroot\assets\images\gallery\categories\circular-categories\12.png" />
    <None Include="wwwroot\assets\images\gallery\categories\grid-categories\01.png" />
    <None Include="wwwroot\assets\images\gallery\categories\grid-categories\02.png" />
    <None Include="wwwroot\assets\images\gallery\categories\grid-categories\03.png" />
    <None Include="wwwroot\assets\images\gallery\categories\grid-categories\04.png" />
    <None Include="wwwroot\assets\images\gallery\categories\grid-categories\05.png" />
    <None Include="wwwroot\assets\images\gallery\categories\grid-categories\06.png" />
    <None Include="wwwroot\assets\images\gallery\categories\grid-categories\07.png" />
    <None Include="wwwroot\assets\images\gallery\categories\grid-categories\08.png" />
    <None Include="wwwroot\assets\images\gallery\categories\grid-categories\09.png" />
    <None Include="wwwroot\assets\images\gallery\categories\grid-categories\10.png" />
    <None Include="wwwroot\assets\images\gallery\categories\grid-categories\11.png" />
    <None Include="wwwroot\assets\images\gallery\categories\grid-categories\12.png" />
    <None Include="wwwroot\assets\images\gallery\deals\01.png" />
    <None Include="wwwroot\assets\images\gallery\deals\02.png" />
    <None Include="wwwroot\assets\images\gallery\deals\03.png" />
    <None Include="wwwroot\assets\images\gallery\deals\04.png" />
    <None Include="wwwroot\assets\images\gallery\deals\05.png" />
    <None Include="wwwroot\assets\images\gallery\google-play-store.png" />
    <None Include="wwwroot\assets\images\gallery\logo.png" />
    <None Include="wwwroot\assets\images\gallery\mega-menu-img-1.jpg" />
    <None Include="wwwroot\assets\images\gallery\mega-menu-img-2.jpg" />
    <None Include="wwwroot\assets\images\gallery\mega-menu-img-3.jpg" />
    <None Include="wwwroot\assets\images\gallery\mega-menu-img-4.jpg" />
    <None Include="wwwroot\assets\images\gallery\page-header\page-header-1.png" />
    <None Include="wwwroot\assets\images\gallery\page-header\page-header-2.png" />
    <None Include="wwwroot\assets\images\gallery\pages\about-us.png" />
    <None Include="wwwroot\assets\images\gallery\pages\vision.png" />
    <None Include="wwwroot\assets\images\gallery\payment\amazon-pay.png" />
    <None Include="wwwroot\assets\images\gallery\payment\money.png" />
    <None Include="wwwroot\assets\images\gallery\payment\paypal.png" />
    <None Include="wwwroot\assets\images\gallery\payment\stripe.png" />
    <None Include="wwwroot\assets\images\gallery\payment\visa.png" />
    <None Include="wwwroot\assets\images\gallery\product-images\01.png" />
    <None Include="wwwroot\assets\images\gallery\product-images\02.png" />
    <None Include="wwwroot\assets\images\gallery\product-images\03.png" />
    <None Include="wwwroot\assets\images\gallery\product-images\04.png" />
    <None Include="wwwroot\assets\images\gallery\product-images\05.png" />
    <None Include="wwwroot\assets\images\gallery\search-box\01.png" />
    <None Include="wwwroot\assets\images\gallery\search-box\02.png" />
    <None Include="wwwroot\assets\images\gallery\search-box\03.png" />
    <None Include="wwwroot\assets\images\gallery\search-box\04.png" />
    <None Include="wwwroot\assets\images\gallery\search-box\05.png" />
    <None Include="wwwroot\assets\images\gallery\slider\slide-1.png" />
    <None Include="wwwroot\assets\images\gallery\slider\slide-2.png" />
    <None Include="wwwroot\assets\images\gallery\slider\slide-3.png" />
    <None Include="wwwroot\assets\images\gallery\slider\slide-4.png" />
    <None Include="wwwroot\assets\images\gallery\slider\slide-5.png" />
    <None Include="wwwroot\assets\images\gallery\tabular-product\01.png" />
    <None Include="wwwroot\assets\images\gallery\tabular-product\02.png" />
    <None Include="wwwroot\assets\images\gallery\tabular-product\03.png" />
    <None Include="wwwroot\assets\images\gallery\tabular-product\04.png" />
    <None Include="wwwroot\assets\images\gallery\tabular-product\05.png" />
    <None Include="wwwroot\assets\images\gallery\tabular-product\06.png" />
    <None Include="wwwroot\assets\images\gallery\tabular-product\07.png" />
    <None Include="wwwroot\assets\images\gallery\tabular-product\08.png" />
    <None Include="wwwroot\assets\images\gallery\team\01.png" />
    <None Include="wwwroot\assets\images\gallery\team\02.png" />
    <None Include="wwwroot\assets\images\gallery\team\03.png" />
    <None Include="wwwroot\assets\images\gallery\team\04.png" />
    <None Include="wwwroot\assets\js\bootstrap.bundle.min.js" />
    <None Include="wwwroot\assets\js\index.js" />
    <None Include="wwwroot\assets\js\jquery.min.js" />
    <None Include="wwwroot\assets\js\main.js" />
    <None Include="wwwroot\assets\js\price_range_script.js" />
    <None Include="wwwroot\assets\js\product-details.js" />
    <None Include="wwwroot\assets\js\search-slider.js" />
    <None Include="wwwroot\assets\plugins\swiper\css\swiper-bundle.min.css" />
    <None Include="wwwroot\assets\plugins\swiper\js\swiper-bundle.min.js" />
    <None Include="wwwroot\assets\sass\style.css" />
    <None Include="wwwroot\assets\sass\style.css.map" />
    <None Include="wwwroot\assets\sass\style.scss" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.31" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.31">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecommerce.Application\Ecommerce.Application.csproj" />
    <ProjectReference Include="..\Ecommerce.Infrastructure\Ecommerce.Infrastructure.csproj" />
  </ItemGroup>

</Project>
